Resources:
  CalendarTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${self:custom.calendarEvent.dynamoTableName}
      AttributeDefinitions:
        - AttributeName: 'targetCalendarId'
          AttributeType: 'S'
        - AttributeName: 'startTimestamp'
          AttributeType: 'N'
      KeySchema:
        - AttributeName: 'targetCalendarId'
          KeyType: 'HASH'
        - AttributeName: 'startTimestamp'
          KeyType: 'RANGE'
      BillingMode: 'PAY_PER_REQUEST'
